### ISSUE TITLE
Training configurations for 23.9B tokens

### ISSUE THREAD

**Issue by Nandan91** [languini-kitchen/languini-kitchen#13]
Thanks for creating datasets for researchers with fewer GPUs! 

The training configurations are given for 6h to 96h (up to 5.7B tokens). 

Given that I can use 4 GPUs to train a single model, I would like to know the recommended training settings for models beyond 5.7B (say, on full 23.9B tokens, either GPT-2 small or medium models).  

Thanks!

**Comment by ischlag** [comment]
Hi @Nandan91 thank you for your interest. A small correction: we did not create the books3 dataset, we merely filtered it. 

The main basis of comparison in this repo is gpu-hours, specifically on the RTX 3090 for most of the experiments we provide. To go beyond 96h, e.g. another factor 2 to 192h you should compute your models throughput on a single RTX 3090 and use that throughput to compute the total number of tokens you are allowed to consume within that theoretical time frame. 

Note that the throughput is measured on a reference GPU. You can train your model on multiple GPUs or different GPUs but you would have to adhere to the total number of tokens you have computed.
